### ISSUE TITLE
determined evaluation of or/xor gateways

### ISSUE THREAD

**Issue by rathaustreppe** [rathaustreppe/bpmn-analyser#10]
Hey there,

currently the branching into multiple paths at exclusive and inclusive bpmn-gateways work entirely determined: According to the branch rules on the sequence flows it is decided into which branch the graph-pointer will branch into. Those branch rules only check the current token state. This state is always the same when executing the diagram multiple times. Therefore it cannot happen, that graph-pointer will ever branch into a different path.

Have a look at this diagram:
![g4873](https://user-images.githubusercontent.com/68727256/96985861-25f74c00-1521-11eb-8c52-676f3ed8f72b.png)

The problem with this determined behaviour is, that the token-based semantic checks (== the core of the program) will never check another path. Therefore it cannot tell, if this part of the diagram was modelled correctly. E.g. if the 'bar'-branch is correct.

**Comment by LostInDarkMath** [comment]
Is this kind of the same problem like checking dead code in a program?

**Comment by rathaustreppe** [comment]
> 
> 
> Is this kind of the same problem like checking dead code in a program?

Its more like that the functionality to check if there is dead code is not working ^^

**Comment by rathaustreppe** [comment]
Fixed this issue by introducing a new concept >scenarios<. Like in real world buisness processes have different cases. Now ppl can define those and run multiple instances of the token through the diagram. Each instance will take a different path.
Will be linked in an upcomming pull request.
